<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitaff6f915f4c70d2ad7771c0fdf2cf946
{
    public static $prefixLengthsPsr4 = array (
        'H' => 
        array (
            'Hari\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Hari\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Inc',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitaff6f915f4c70d2ad7771c0fdf2cf946::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitaff6f915f4c70d2ad7771c0fdf2cf946::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
